name: samtools_fastq
description: |
  Convert a BAM back to FASTQ.
keywords:
  - fastq
  - bam
  - samtools
tools:
  - samtools:
      description: |
        samtools

input:
  - bam:
      type: map/file
      description: |
        Sample metadata map and a BAM.
      pattern: "tuple val(meta), path(bam)"

output:
  - reads:
      type: map/file
      description: |
        Reads extracted from the BAM.
      pattern: "tuple val(meta), path(*.fastq.gz)"

authors:
  - "EIT Generative Biology Institute"
